spring.application.name=user-service
server.port=8081
spring.datasource.url=jdbc:mysql://127.0.0.1:5506/garzonpro_user?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# Cambia temporalmente de 'none' a 'update'
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true